/**
 * Generators for the Next.js (App Router, TypeScript) project files.
 *
 * Strategy: max-fidelity port. Each section is a Server Component that renders
 * its original HTML via `dangerouslySetInnerHTML`, so Webflow's runtime JS,
 * IX2 animations, Swiper, inline SVGs, and arbitrary attribute namespaces all
 * survive intact. The page is rendered statically (`output: 'export'`) so the
 * result is a deployable static site, no SSR runtime required.
 */

export interface NextProjectMeta {
  /** Origin hostname, used for the project name and metadata. */
  hostname: string;
  /** Original page title. */
  title: string;
  /** Class string preserved on <body>. */
  bodyClass: string;
  /** Extra body attrs (data-wf-page, data-wf-site, etc.) */
  bodyAttrs: Record<string, string>;
  /** Raw <head> inner HTML (links, inline styles, inline scripts, meta). */
  headHtml: string;
  /** Raw HTML of <script>/<noscript>/<style> tags emitted at the end of <body>. */
  bodyScriptsHtml: string;
  /** Section components in render order. */
  sections: Array<{ name: string; fileName: string }>;
}

const NEXT_VERSION = '15.0.0';
const REACT_VERSION = '18.3.1';

function safeProjectName(hostname: string): string {
  return (
    hostname
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'cleave-site'
  );
}

export function packageJson(meta: NextProjectMeta): string {
  return JSON.stringify(
    {
      name: safeProjectName(meta.hostname),
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        export: 'next build',
      },
      dependencies: {
        next: `^${NEXT_VERSION}`,
        react: `^${REACT_VERSION}`,
        'react-dom': `^${REACT_VERSION}`,
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        '@types/react': '^18.3.0',
        '@types/react-dom': '^18.3.0',
        typescript: '^5.6.0',
      },
    },
    null,
    2,
  );
}

export const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

export const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  // Static export so the output is a portable static site (no Node runtime needed).
  // Run \`npm run build\` and deploy the generated /out folder.
  output: 'export',
  trailingSlash: true,
  images: { unoptimized: true },
  // Skip type-checking + linting during build for max import success across messy real-world HTML.
  typescript: { ignoreBuildErrors: true },
  eslint: { ignoreDuringBuilds: true },
};

module.exports = nextConfig;
`;

export const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

export const GITIGNORE = `node_modules
.next
out
.DS_Store
*.log
.env*.local
`;

export const README_MD = (meta: NextProjectMeta) => `# ${safeProjectName(meta.hostname)}

This Next.js project was generated by **[Cleave](https://github.com/Raghdkun/Cleave)** from
\`${meta.hostname}\`.

## Architecture

- **Stack**: Next.js (App Router) + React 18 + TypeScript, configured for static export
  (\`next build\` produces a portable \`/out\` folder).
- **Components**: each top-level page section is a separate Server Component under
  \`components/\`. To preserve the original site's exact behaviour (IX2 scroll
  animations, Swiper carousels, Webflow runtime JS, inline SVGs with their full
  attribute set), each component renders its captured HTML via
  \`dangerouslySetInnerHTML\`. CSS files and \`<script>\` tags from the original site
  are loaded as-is from \`/public/assets/\`.
- **Assets**: every image, font, CSS file, JS bundle, and media file from the
  original site lives under \`public/assets/\`. Paths are root-absolute.

## Getting started

\`\`\`bash
npm install
npm run dev
# open http://localhost:3000
\`\`\`

## Build for production

\`\`\`bash
npm run build
# output: ./out (deploy to Vercel, Netlify, S3, GitHub Pages, etc.)
\`\`\`

## Customizing a section

Each section in \`components/\` is a self-contained component. To turn one into
real React (state, props, conditional rendering), open the file and replace the
\`dangerouslySetInnerHTML\` block with hand-written JSX. The rest of the page
keeps working unchanged.
`;

/**
 * layout.tsx — server component that renders the document shell. The original
 * <head> children and body-level <script>/<noscript>/<style> tags are passed as
 * raw strings into <SiteBootstrap />, a CLIENT component that injects them via
 * useEffect AFTER hydration. This avoids React hydration mismatches (#418/#425)
 * caused by mutating the DOM before React reconciles it, and lets the original
 * scripts (jQuery, webflow.js, GA, IX2, swiper) load and execute against the
 * fully-rendered section DOM.
 */
export function layoutTsx(meta: NextProjectMeta): string {
  const bodyAttrLines = Object.entries(meta.bodyAttrs)
    .map(([k, v]) => `        ${JSON.stringify(k)}={${JSON.stringify(v)}}`)
    .join('\n');

  return `import type { Metadata } from 'next';
import './globals.css';
import { SiteBootstrap } from '@/components/_bootstrap';

export const metadata: Metadata = {
  title: ${JSON.stringify(meta.title || safeProjectName(meta.hostname))},
};

const HEAD_HTML = ${JSON.stringify(meta.headHtml)};
const BODY_SCRIPTS_HTML = ${JSON.stringify(meta.bodyScriptsHtml)};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body
        className=${JSON.stringify(meta.bodyClass)}
        suppressHydrationWarning${bodyAttrLines ? '\n' + bodyAttrLines : ''}
      >
        {children}
        <SiteBootstrap headHtml={HEAD_HTML} bodyScriptsHtml={BODY_SCRIPTS_HTML} />
      </body>
    </html>
  );
}
`;
}

/**
 * SiteBootstrap.tsx — client component, renders nothing. On mount it parses
 * the captured HEAD_HTML and BODY_SCRIPTS_HTML strings and appends each node
 * to document.head / document.body, recreating <script> elements via
 * document.createElement so the browser actually executes them. Runs once and
 * exits early on subsequent mounts (HMR / fast-refresh safety).
 */
export const SITE_BOOTSTRAP_TSX = `'use client';

import { useEffect } from 'react';

interface SiteBootstrapProps {
  headHtml: string;
  bodyScriptsHtml: string;
}

declare global {
  interface Window {
    __cleaveBootstrapped?: boolean;
  }
}

/**
 * Clones a node into a target parent, recreating <script> elements via
 * document.createElement so the browser actually executes them. For external
 * scripts we await load before resolving so callers can preserve original
 * document order (browsers don't guarantee execution order for scripts that
 * are appended programmatically — only for scripts present at parse time).
 */
function appendNode(parent: HTMLElement, node: Node): Promise<void> {
  if (node.nodeType !== 1) {
    parent.appendChild(node.cloneNode(true));
    return Promise.resolve();
  }
  const el = node as HTMLElement;
  const tag = el.tagName.toLowerCase();
  if (tag !== 'script') {
    parent.appendChild(el.cloneNode(true));
    return Promise.resolve();
  }
  const ns = document.createElement('script');
  for (let i = 0; i < el.attributes.length; i++) {
    const a = el.attributes[i];
    ns.setAttribute(a.name, a.value);
  }
  const src = ns.getAttribute('src');
  // Inline script: appendChild executes synchronously, so we're done.
  if (!src) {
    ns.text = el.textContent || '';
    parent.appendChild(ns);
    return Promise.resolve();
  }
  // Async/defer scripts: fire-and-forget — original page didn't depend on order.
  if (ns.async || ns.defer) {
    parent.appendChild(ns);
    return Promise.resolve();
  }
  // Classic external script: must wait for it to load before continuing so
  // dependent inline scripts (e.g. WebFont.load(...) using webfont.js) don't
  // run before the dependency is defined.
  return new Promise<void>((resolve) => {
    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      resolve();
    };
    ns.addEventListener('load', finish, { once: true });
    ns.addEventListener('error', finish, { once: true });
    parent.appendChild(ns);
  });
}

async function injectInOrder(html: string, target: HTMLElement) {
  const tpl = document.createElement('template');
  tpl.innerHTML = html;
  const nodes = Array.from(tpl.content.childNodes);
  for (const n of nodes) {
    try {
      await appendNode(target, n);
    } catch (err) {
      // Inline scripts can throw synchronously during appendChild (e.g. a
      // missing global). Swallow so a single faulty tag doesn't break the
      // rest of the injection chain (esp. jquery/webflow.js in body).
      // eslint-disable-next-line no-console
      console.warn('[cleave] script failed to execute', err);
    }
  }
}

export function SiteBootstrap({ headHtml, bodyScriptsHtml }: SiteBootstrapProps) {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (window.__cleaveBootstrapped) return;
    window.__cleaveBootstrapped = true;

    (async () => {
      // Hoist original <head> contents (CSS links, inline <style>, jQuery,
      // WebFont loader) IN ORDER so dependency chains hold.
      if (headHtml) await injectInOrder(headHtml, document.head);
      // Then body-level scripts (webflow.js, GA, structured data) AFTER head
      // is fully ready, so things like webflow.js can find jQuery + the DOM.
      if (bodyScriptsHtml) await injectInOrder(bodyScriptsHtml, document.body);
    })();
  }, [headHtml, bodyScriptsHtml]);

  return null;
}
`;

export function pageTsx(meta: NextProjectMeta): string {
  const imports = meta.sections
    .map((s) => `import { ${s.name} } from '@/components/${s.fileName}';`)
    .join('\n');
  const renders = meta.sections.map((s) => `      <${s.name} />`).join('\n');

  return `${imports}

export default function Page() {
  return (
    <>
${renders}
    </>
  );
}
`;
}

export function sectionTsx(name: string, html: string): string {
  return `// Auto-generated by Cleave from the original site.
// Renders the captured HTML verbatim so Webflow IX2 / Swiper / inline SVGs / runtime JS
// continue to work. Replace with hand-written JSX to introduce React state or props.
//
// suppressHydrationWarning: webflow.js mutates DOM (adds w-mod-* classes,
// rewrites styles, attaches event handlers) after mount; we don't want React
// to warn or unmount any of that.
const HTML = ${JSON.stringify(html)};

export function ${name}() {
  return (
    <div
      data-cleave-section=${JSON.stringify(name)}
      suppressHydrationWarning
      dangerouslySetInnerHTML={{ __html: HTML }}
    />
  );
}
`;
}

/**
 * A minimal global stylesheet — the real styling comes from the original site's
 * CSS files, which are loaded by the <link> tags preserved in HEAD_HTML.
 */
export const GLOBALS_CSS = `/* Globals: minimal reset so the original site's CSS owns presentation. */
html, body { margin: 0; padding: 0; }
[data-cleave-section] { display: contents; }
`;
