/**
 * Generators for the Next.js (App Router, TypeScript) project files.
 *
 * Strategy: max-fidelity port. Each section is a Server Component that renders
 * its original HTML via `dangerouslySetInnerHTML`, so Webflow's runtime JS,
 * IX2 animations, Swiper, inline SVGs, and arbitrary attribute namespaces all
 * survive intact. The page is rendered statically (`output: 'export'`) so the
 * result is a deployable static site, no SSR runtime required.
 */

export interface NextProjectMeta {
  /** Origin hostname, used for the project name and metadata. */
  hostname: string;
  /** Original page title. */
  title: string;
  /** Class string preserved on <body>. */
  bodyClass: string;
  /** Extra body attrs (data-wf-page, data-wf-site, etc.) */
  bodyAttrs: Record<string, string>;
  /** Raw <head> inner HTML (links, inline styles, inline scripts, meta). */
  headHtml: string;
  /** Raw HTML of <script>/<noscript>/<style> tags emitted at the end of <body>. */
  bodyScriptsHtml: string;
  /** Section components in render order. */
  sections: Array<{ name: string; fileName: string }>;
}

const NEXT_VERSION = '15.0.0';
const REACT_VERSION = '18.3.1';

function safeProjectName(hostname: string): string {
  return (
    hostname
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'cleave-site'
  );
}

export function packageJson(meta: NextProjectMeta): string {
  return JSON.stringify(
    {
      name: safeProjectName(meta.hostname),
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        export: 'next build',
      },
      dependencies: {
        next: `^${NEXT_VERSION}`,
        react: `^${REACT_VERSION}`,
        'react-dom': `^${REACT_VERSION}`,
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        '@types/react': '^18.3.0',
        '@types/react-dom': '^18.3.0',
        typescript: '^5.6.0',
      },
    },
    null,
    2,
  );
}

export const TSCONFIG_JSON = JSON.stringify(
  {
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  },
  null,
  2,
);

export const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  // Static export so the output is a portable static site (no Node runtime needed).
  // Run \`npm run build\` and deploy the generated /out folder.
  output: 'export',
  trailingSlash: true,
  images: { unoptimized: true },
  // Skip type-checking + linting during build for max import success across messy real-world HTML.
  typescript: { ignoreBuildErrors: true },
  eslint: { ignoreDuringBuilds: true },
};

module.exports = nextConfig;
`;

export const NEXT_ENV_DTS = `/// <reference types="next" />
/// <reference types="next/image-types/global" />
`;

export const GITIGNORE = `node_modules
.next
out
.DS_Store
*.log
.env*.local
`;

export const README_MD = (meta: NextProjectMeta) => `# ${safeProjectName(meta.hostname)}

This Next.js project was generated by **[Cleave](https://github.com/Raghdkun/Cleave)** from
\`${meta.hostname}\`.

## Architecture

- **Stack**: Next.js (App Router) + React 18 + TypeScript, configured for static export
  (\`next build\` produces a portable \`/out\` folder).
- **Components**: each top-level page section is a separate Server Component under
  \`components/\`. To preserve the original site's exact behaviour (IX2 scroll
  animations, Swiper carousels, Webflow runtime JS, inline SVGs with their full
  attribute set), each component renders its captured HTML via
  \`dangerouslySetInnerHTML\`. CSS files and \`<script>\` tags from the original site
  are loaded as-is from \`/public/assets/\`.
- **Assets**: every image, font, CSS file, JS bundle, and media file from the
  original site lives under \`public/assets/\`. Paths are root-absolute.

## Getting started

\`\`\`bash
npm install
npm run dev
# open http://localhost:3000
\`\`\`

## Build for production

\`\`\`bash
npm run build
# output: ./out (deploy to Vercel, Netlify, S3, GitHub Pages, etc.)
\`\`\`

## Customizing a section

Each section in \`components/\` is a self-contained component. To turn one into
real React (state, props, conditional rendering), open the file and replace the
\`dangerouslySetInnerHTML\` block with hand-written JSX. The rest of the page
keeps working unchanged.
`;

/**
 * layout.tsx — renders <html><head>{originalHeadHtml}</head><body class="..." data-...>{children}</body></html>.
 * `suppressHydrationWarning` is added because Webflow's inline JS often mutates
 * documentElement classes (e.g. `w-mod-js`, `w-mod-touch`) before React hydrates.
 */
export function layoutTsx(meta: NextProjectMeta): string {
  const bodyAttrLines = Object.entries(meta.bodyAttrs)
    .map(([k, v]) => `        ${JSON.stringify(k)}={${JSON.stringify(v)}}`)
    .join('\n');

  return `import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: ${JSON.stringify(meta.title || safeProjectName(meta.hostname))},
};

const HEAD_HTML = ${JSON.stringify(meta.headHtml)};
const BODY_SCRIPTS_HTML = ${JSON.stringify(meta.bodyScriptsHtml)};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="cleave-head-marker" data-cleave="true" />
      </head>
      <body
        className=${JSON.stringify(meta.bodyClass)}
        suppressHydrationWarning${bodyAttrLines ? '\n' + bodyAttrLines : ''}
      >
        {/* Original <head> contents (links, inline styles, inline scripts) re-emitted
            in <body> via a hidden marker + script that hoists them to <head> on first paint.
            This keeps Next.js's <head> management intact while preserving every original tag. */}
        <div
          data-cleave-head-html
          style={{ display: 'none' }}
          dangerouslySetInnerHTML={{ __html: HEAD_HTML }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: \`(function(){var s=document.querySelector('[data-cleave-head-html]');if(!s)return;var nodes=Array.from(s.childNodes);var head=document.head;nodes.forEach(function(n){if(n.nodeType===1){var tag=n.tagName.toLowerCase();if(tag==='script'){var ns=document.createElement('script');for(var i=0;i<n.attributes.length;i++){var a=n.attributes[i];ns.setAttribute(a.name,a.value);}ns.text=n.textContent||'';head.appendChild(ns);}else{head.appendChild(n.cloneNode(true));}}});s.parentNode.removeChild(s);})();\`,
          }}
        />
        {children}
        {/* Body-level scripts from the original page (webflow.js, jquery, GA, etc.).
            They are mounted after the section components so they can find the DOM
            they expect (IX2 lookups, swiper init, form bindings). */}
        <div
          data-cleave-body-scripts
          style={{ display: 'none' }}
          dangerouslySetInnerHTML={{ __html: BODY_SCRIPTS_HTML }}
        />
        <script
          dangerouslySetInnerHTML={{
            __html: \`(function(){var s=document.querySelector('[data-cleave-body-scripts]');if(!s)return;var nodes=Array.from(s.childNodes);var body=document.body;nodes.forEach(function(n){if(n.nodeType===1){var tag=n.tagName.toLowerCase();if(tag==='script'){var ns=document.createElement('script');for(var i=0;i<n.attributes.length;i++){var a=n.attributes[i];ns.setAttribute(a.name,a.value);}ns.text=n.textContent||'';body.appendChild(ns);}else{body.appendChild(n.cloneNode(true));}}});s.parentNode.removeChild(s);})();\`,
          }}
        />
      </body>
    </html>
  );
}
`;
}

export function pageTsx(meta: NextProjectMeta): string {
  const imports = meta.sections
    .map((s) => `import { ${s.name} } from '@/components/${s.fileName}';`)
    .join('\n');
  const renders = meta.sections.map((s) => `      <${s.name} />`).join('\n');

  return `${imports}

export default function Page() {
  return (
    <>
${renders}
    </>
  );
}
`;
}

export function sectionTsx(name: string, html: string): string {
  return `// Auto-generated by Cleave from the original site.
// Renders the captured HTML verbatim so Webflow IX2 / Swiper / inline SVGs / runtime JS
// continue to work. Replace with hand-written JSX to introduce React state or props.
const HTML = ${JSON.stringify(html)};

export function ${name}() {
  return <div data-cleave-section=${JSON.stringify(name)} dangerouslySetInnerHTML={{ __html: HTML }} />;
}
`;
}

/**
 * A minimal global stylesheet — the real styling comes from the original site's
 * CSS files, which are loaded by the <link> tags preserved in HEAD_HTML.
 */
export const GLOBALS_CSS = `/* Globals: minimal reset so the original site's CSS owns presentation. */
html, body { margin: 0; padding: 0; }
[data-cleave-section] { display: contents; }
`;
