import JSZip from 'jszip';
import type { AssetRecord } from './types.js';
import { logger } from './utils/logger.js';

const README_TXT = `Cleave - Exported Website
==========================

IMPORTANT: This site uses ES modules (import/export). Modern browsers
BLOCK ES modules when an HTML file is opened directly via file:// for
security (CORS). If you double-click index.html you will see a blank
page or missing animations / scroll effects.

You MUST serve this folder over HTTP. Easiest options:

  macOS / Linux:
    ./start.sh

  Windows:
    start.bat

  Or manually (any one):
    python3 -m http.server 8000
    npx serve .
    php -S localhost:8000

Then open: http://localhost:8000/

If your entry page is inside a sub-folder (e.g. /en/), open
http://localhost:8000/en/ instead.
`;

const START_SH = `#!/usr/bin/env bash
# Auto-generated by Cleave. Serves the exported site over HTTP so
# ES modules + scroll animations work correctly.
set -e
cd "$(dirname "$0")"
PORT=\${PORT:-8000}

open_url() {
  local url="$1"
  if command -v open >/dev/null 2>&1; then open "$url"
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
  fi
}

if command -v python3 >/dev/null 2>&1; then
  echo "Serving on http://localhost:$PORT/"
  (sleep 1 && open_url "http://localhost:$PORT/") &
  exec python3 -m http.server "$PORT"
elif command -v python >/dev/null 2>&1; then
  echo "Serving on http://localhost:$PORT/"
  (sleep 1 && open_url "http://localhost:$PORT/") &
  exec python -m SimpleHTTPServer "$PORT"
elif command -v npx >/dev/null 2>&1; then
  echo "Serving on http://localhost:$PORT/ via npx serve"
  exec npx --yes serve -l "$PORT" .
elif command -v php >/dev/null 2>&1; then
  echo "Serving on http://localhost:$PORT/ via php"
  (sleep 1 && open_url "http://localhost:$PORT/") &
  exec php -S "localhost:$PORT"
else
  echo "ERROR: need python3, npx, or php installed to serve this folder."
  exit 1
fi
`;

const START_BAT = `@echo off
REM Auto-generated by Cleave. Serves the exported site over HTTP so
REM ES modules + scroll animations work correctly.
cd /d "%~dp0"
set PORT=8000

where python >nul 2>nul
if %errorlevel%==0 (
  echo Serving on http://localhost:%PORT%/
  start "" "http://localhost:%PORT%/"
  python -m http.server %PORT%
  goto :eof
)

where npx >nul 2>nul
if %errorlevel%==0 (
  echo Serving on http://localhost:%PORT%/ via npx serve
  npx --yes serve -l %PORT% .
  goto :eof
)

where php >nul 2>nul
if %errorlevel%==0 (
  echo Serving on http://localhost:%PORT%/ via php
  start "" "http://localhost:%PORT%/"
  php -S localhost:%PORT%
  goto :eof
)

echo ERROR: need python, npx, or php installed to serve this folder.
pause
`;

function addLauncher(zip: JSZip): void {
  zip.file('README.txt', README_TXT);
  // unix exec bit (0755)
  zip.file('start.sh', START_SH, {
    unixPermissions: parseInt('755', 8),
  });
  zip.file('start.bat', START_BAT);
}

export async function bundle(
  html: string,
  assets: Map<string, AssetRecord>,
): Promise<Buffer> {
  const zip = new JSZip();

  zip.file('index.html', html);

  for (const [, record] of assets) {
    zip.file(record.localPath, record.content, { binary: true });
  }

  addLauncher(zip);

  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
    platform: 'UNIX',
  });

  const totalFiles = 1 + assets.size;
  logger.info('ZIP created', {
    files: totalFiles,
    size: `${(zipBuffer.length / 1024).toFixed(1)} KB`,
  });

  return zipBuffer;
}

export async function bundleSite(
  pages: Array<{ localPath: string; html: string }>,
  assets: Map<string, AssetRecord>,
): Promise<Buffer> {
  const zip = new JSZip();

  for (const page of pages) {
    zip.file(page.localPath, page.html);
  }

  for (const [, record] of assets) {
    zip.file(record.localPath, record.content, { binary: true });
  }

  addLauncher(zip);

  const zipBuffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
    platform: 'UNIX',
  });

  const totalFiles = pages.length + assets.size;
  logger.info('Site ZIP created', {
    pages: pages.length,
    assets: assets.size,
    totalFiles,
    size: `${(zipBuffer.length / 1024).toFixed(1)} KB`,
  });

  return zipBuffer;
}
